name: health-check

on:
  schedule:
    - cron: "30 8,14,20 * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run health check
        run: |
          chmod +x health.sh
          bash health.sh

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "health check update"
          file_pattern: "readme.md"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
